import { createSupabaseAdminClient } from '@/lib/server/supabaseServer';
import { Launch } from '@/lib/types/launch';

export async function refreshPublicCache({ launches, tier }: { launches: Launch[]; tier?: string }) {
  const supabase = createSupabaseAdminClient();
  const rows = launches.map((l) => {
    return {
      launch_id: l.id,
      ll2_launch_uuid: l.ll2Id,
      ll2_agency_id: l.ll2AgencyId ?? null,
      ll2_pad_id: l.ll2PadId ?? null,
      ll2_rocket_config_id: l.ll2RocketConfigId ?? null,
      name: l.name,
      slug: l.slug ?? null,
      launch_designator: l.launchDesignator,
      agency_launch_attempt_count: l.agencyLaunchAttemptCount,
      agency_launch_attempt_count_year: l.agencyLaunchAttemptCountYear,
      location_launch_attempt_count: l.locationLaunchAttemptCount,
      location_launch_attempt_count_year: l.locationLaunchAttemptCountYear,
      orbital_launch_attempt_count: l.orbitalLaunchAttemptCount,
      orbital_launch_attempt_count_year: l.orbitalLaunchAttemptCountYear,
      pad_launch_attempt_count: l.padLaunchAttemptCount,
      pad_launch_attempt_count_year: l.padLaunchAttemptCountYear,
      pad_turnaround: l.padTurnaround,
      mission_patches: l.missionPatches,
      updates: l.updates,
      timeline: l.timeline,
      image_url: l.image.full,
      image_credit: l.image.credit,
      image_license_name: l.image.license,
      image_license_url: l.image.licenseUrl,
      image_single_use: l.image.singleUse,
      provider: l.provider,
      provider_type: l.providerType,
      provider_country_code: l.providerCountryCode,
      provider_description: l.providerDescription,
      vehicle: l.vehicle,
      rocket_full_name: l.rocket?.fullName,
      rocket_family: l.rocket?.family,
      rocket_manufacturer: l.rocket?.manufacturer,
      rocket_manufacturer_logo_url: l.rocket?.manufacturerLogoUrl,
      rocket_manufacturer_image_url: l.rocket?.manufacturerImageUrl,
      rocket_description: l.rocket?.description,
      rocket_image_url: l.rocket?.imageUrl,
      rocket_variant: l.rocket?.variant,
      rocket_length_m: l.rocket?.lengthM,
      rocket_diameter_m: l.rocket?.diameterM,
      rocket_reusable: l.rocket?.reusable,
      rocket_maiden_flight: l.rocket?.maidenFlight,
      rocket_leo_capacity: l.rocket?.leoCapacity,
      rocket_gto_capacity: l.rocket?.gtoCapacity,
      rocket_launch_mass: l.rocket?.launchMass,
      rocket_launch_cost: l.rocket?.launchCost,
      rocket_info_url: l.rocket?.infoUrl,
      rocket_wiki_url: l.rocket?.wikiUrl,
      mission_name: l.mission?.name,
      mission_type: l.mission?.type,
      mission_orbit: l.mission?.orbit,
      mission_description: l.mission?.description,
      mission_info_urls: l.mission?.infoUrls,
      mission_vid_urls: l.mission?.vidUrls,
      mission_agencies: l.mission?.agencies,
      launch_info_urls: l.launchInfoUrls,
      launch_vid_urls: l.launchVidUrls,
      flightclub_url: l.flightclubUrl,
      hashtag: l.hashtag,
      probability: l.probability,
      weather_concerns: l.weatherConcerns ?? null,
      weather_icon_url: l.weatherIconUrl ?? null,
      hold_reason: l.holdReason,
      fail_reason: l.failReason,
      programs: l.programs,
      crew: l.crew,
      payloads: l.payloads,
      net: l.net,
      net_precision: l.netPrecision,
      window_start: l.windowStart,
      window_end: l.windowEnd,
      status_name: l.status,
      status_abbrev: l.statusText,
      tier: l.tier,
      featured: l.featured ?? false,
      pad_name: l.pad.name,
      pad_short_code: l.pad.shortCode,
      pad_state: l.pad.state,
      pad_state_code: l.pad.state,
      pad_timezone: l.pad.timezone,
      location_name: l.pad.locationName || l.pad.name,
      pad_location_name: l.pad.locationName || l.pad.name,
      pad_country_code: l.pad.countryCode,
      pad_map_url: l.pad.mapUrl,
      pad_latitude: l.pad.latitude ?? null,
      pad_longitude: l.pad.longitude ?? null,
      provider_logo_url: l.providerLogoUrl,
      provider_image_url: l.providerImageUrl,
      image_thumbnail_url: l.image.thumbnail,
      webcast_live: l.webcastLive,
      video_url: l.videoUrl,
      cache_generated_at: new Date().toISOString()
    };
  });

  const { error } = await supabase.from('launches_public_cache').upsert(rows, { onConflict: 'launch_id' });
  if (error) console.error('refreshPublicCache error', error);
}
