export const SATELLITE_OWNER_ALIASES: Record<string, string> = {
  ARGN: 'Argentina',
  AUS: 'Australia',
  BEL: 'Belgium',
  BERM: 'Bermuda',
  BOL: 'Bolivia',
  BRAZ: 'Brazil',
  CA: 'Canada',
  CHLE: 'Chile',
  CHBZ: 'China/Brazil',
  CIS: 'Commonwealth of Independent States',
  CZCH: 'Czech Republic',
  DEN: 'Denmark',
  ESA: 'European Space Agency',
  EST: 'Estonia',
  EUME: 'EUMETSAT',
  FR: 'France',
  GER: 'Germany',
  GLOB: 'Globalstar',
  GREC: 'Greece',
  HUN: 'Hungary',
  IND: 'India',
  ISS: 'International Space Station Program',
  IT: 'Italy',
  ITSO: 'Intelsat',
  JPN: 'Japan',
  KAZ: 'Kazakhstan',
  LUXE: 'Luxembourg',
  NICO: 'New ICO',
  NETH: 'Netherlands',
  NOR: 'Norway',
  ORB: 'Orbcomm',
  POL: 'Poland',
  PRC: "People's Republic of China",
  RASC: 'RascomStar',
  SAFR: 'South Africa',
  SES: 'SES',
  SKOR: 'South Korea',
  SPAIN: 'Spain',
  SWE: 'Sweden',
  SWIT: 'Switzerland',
  TBD: 'To be determined',
  THAI: 'Thailand',
  TURK: 'Turkey',
  UK: 'United Kingdom',
  UKR: 'Ukraine',
  UAE: 'United Arab Emirates',
  US: 'United States',
  VTNM: 'Vietnam'
};

export function getSatelliteOwnerAlias(ownerCode: string | null | undefined) {
  const normalized = String(ownerCode || '').trim().toUpperCase();
  if (!normalized) return null;
  return SATELLITE_OWNER_ALIASES[normalized] || null;
}
