-- Enrich launches and public cache with mission/rocket/agency metadata for detail pages.

alter table public.launches
  add column if not exists mission_name text,
  add column if not exists mission_description text,
  add column if not exists mission_type text,
  add column if not exists mission_orbit text,
  add column if not exists mission_agencies jsonb,
  add column if not exists mission_info_urls jsonb,
  add column if not exists mission_vid_urls jsonb,
  add column if not exists rocket_full_name text,
  add column if not exists rocket_family text,
  add column if not exists rocket_description text,
  add column if not exists rocket_manufacturer text,
  add column if not exists rocket_reusable boolean,
  add column if not exists rocket_maiden_flight date,
  add column if not exists rocket_leo_capacity int,
  add column if not exists rocket_gto_capacity int,
  add column if not exists rocket_launch_mass int,
  add column if not exists rocket_launch_cost text,
  add column if not exists rocket_info_url text,
  add column if not exists rocket_wiki_url text,
  add column if not exists provider_type text,
  add column if not exists provider_country_code text,
  add column if not exists provider_description text,
  add column if not exists programs jsonb,
  add column if not exists crew jsonb,
  add column if not exists payloads jsonb,
  add column if not exists pad_location_name text,
  add column if not exists pad_country_code text,
  add column if not exists pad_map_url text;

alter table public.launches_public_cache
  add column if not exists mission_name text,
  add column if not exists mission_type text,
  add column if not exists mission_orbit text,
  add column if not exists mission_agencies jsonb,
  add column if not exists rocket_full_name text,
  add column if not exists rocket_family text,
  add column if not exists rocket_manufacturer text,
  add column if not exists provider_type text,
  add column if not exists provider_country_code text,
  add column if not exists programs jsonb,
  add column if not exists pad_location_name text,
  add column if not exists pad_country_code text;
