-- Provider-aware launch social post ingestion (X-first).

alter table public.launches
  add column if not exists social_primary_post_id text,
  add column if not exists social_primary_post_url text,
  add column if not exists social_primary_post_platform text,
  add column if not exists social_primary_post_handle text,
  add column if not exists social_primary_post_matched_at timestamptz,
  add column if not exists social_primary_post_for_date date;

alter table public.launches_public_cache
  add column if not exists social_primary_post_id text,
  add column if not exists social_primary_post_url text,
  add column if not exists social_primary_post_platform text,
  add column if not exists social_primary_post_handle text,
  add column if not exists social_primary_post_matched_at timestamptz,
  add column if not exists social_primary_post_for_date date;

create table if not exists public.social_accounts (
  id bigint generated by default as identity primary key,
  provider_key text not null,
  provider_name text not null,
  platform text not null default 'x',
  handle text not null,
  priority int not null default 100,
  active boolean not null default true,
  verified_hint boolean not null default true,
  last_fetch_at timestamptz,
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error text,
  cooldown_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint social_accounts_platform_check check (platform in ('x'))
);

create unique index if not exists social_accounts_platform_provider_handle_uidx
  on public.social_accounts(platform, provider_key, handle);

create index if not exists social_accounts_platform_provider_active_idx
  on public.social_accounts(platform, provider_key, active, priority);

alter table public.social_accounts enable row level security;
revoke all on table public.social_accounts from public;
revoke all on table public.social_accounts from anon, authenticated;
grant all on table public.social_accounts to service_role;

create table if not exists public.launch_social_candidates (
  id bigint generated by default as identity primary key,
  launch_id uuid not null references public.launches(id) on delete cascade,
  platform text not null,
  account_handle text not null,
  external_post_id text not null,
  post_url text not null,
  post_text text not null,
  posted_at timestamptz,
  fetched_at timestamptz not null default now(),
  dedupe_key text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint launch_social_candidates_platform_check check (platform in ('x'))
);

create unique index if not exists launch_social_candidates_dedupe_key_uidx
  on public.launch_social_candidates(dedupe_key);

create index if not exists launch_social_candidates_launch_platform_fetched_idx
  on public.launch_social_candidates(launch_id, platform, fetched_at desc);

create index if not exists launch_social_candidates_external_post_idx
  on public.launch_social_candidates(external_post_id);

alter table public.launch_social_candidates enable row level security;
revoke all on table public.launch_social_candidates from public;
revoke all on table public.launch_social_candidates from anon, authenticated;
grant all on table public.launch_social_candidates to service_role;

create table if not exists public.launch_social_matches (
  id bigint generated by default as identity primary key,
  launch_id uuid not null references public.launches(id) on delete cascade,
  platform text not null,
  external_post_id text not null,
  post_url text not null,
  account_handle text not null,
  score int not null,
  confidence text not null,
  matched_at timestamptz not null default now(),
  match_version text not null default 'v1',
  signals_json jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint launch_social_matches_platform_check check (platform in ('x')),
  constraint launch_social_matches_confidence_check check (confidence in ('high', 'none'))
);

create unique index if not exists launch_social_matches_launch_platform_post_uidx
  on public.launch_social_matches(launch_id, platform, external_post_id);

create unique index if not exists launch_social_matches_active_one_uidx
  on public.launch_social_matches(launch_id, platform)
  where active;

create index if not exists launch_social_matches_launch_platform_matched_idx
  on public.launch_social_matches(launch_id, platform, matched_at desc);

alter table public.launch_social_matches enable row level security;
revoke all on table public.launch_social_matches from public;
revoke all on table public.launch_social_matches from anon, authenticated;
grant all on table public.launch_social_matches to service_role;

insert into public.system_settings (key, value)
values
  ('launch_social_enabled', 'true'::jsonb),
  ('launch_social_x_enabled', 'true'::jsonb),
  ('launch_social_timezone', '"America/New_York"'::jsonb),
  ('launch_social_top_n', '3'::jsonb),
  ('launch_social_horizon_days', '7'::jsonb),
  ('launch_social_max_per_run', '30'::jsonb),
  ('launch_social_baseline_minutes', '30'::jsonb),
  ('launch_social_far_minutes', '15'::jsonb),
  ('launch_social_approach_minutes', '5'::jsonb),
  ('launch_social_final_minutes', '2'::jsonb),
  ('launch_social_post_minutes', '30'::jsonb),
  ('launch_social_far_hours', '24'::jsonb),
  ('launch_social_approach_hours', '6'::jsonb),
  ('launch_social_post_hours', '6'::jsonb),
  ('launch_social_match_threshold_high', '70'::jsonb),
  ('launch_social_fetch_timeout_ms', '12000'::jsonb),
  ('launch_social_error_cooldown_minutes', '30'::jsonb),
  ('launch_social_max_accounts_per_provider', '3'::jsonb)
on conflict (key) do nothing;

insert into public.system_settings (key, value)
values ('spacex_x_snapshot_enabled', 'false'::jsonb)
on conflict (key) do update
set
  value = excluded.value,
  updated_at = now();

insert into public.social_accounts (provider_key, provider_name, platform, handle, priority, active, verified_hint)
values
  ('spacex', 'SpaceX', 'x', 'spacex', 10, true, true),
  ('ula', 'United Launch Alliance', 'x', 'ulalaunch', 20, true, true),
  ('rocket-lab', 'Rocket Lab', 'x', 'rocketlab', 30, true, true),
  ('blue-origin', 'Blue Origin', 'x', 'blueorigin', 40, true, true),
  ('arianespace', 'Arianespace', 'x', 'arianespace', 50, true, true)
on conflict (platform, provider_key, handle) do update
set
  provider_name = excluded.provider_name,
  priority = excluded.priority,
  active = excluded.active,
  verified_hint = excluded.verified_hint,
  updated_at = now();

do $$
begin
  if exists (select 1 from cron.job where jobname = 'spacex_x_post_snapshot') then
    perform cron.unschedule('spacex_x_post_snapshot');
  end if;

  if exists (select 1 from cron.job where jobname = 'launch_social_refresh') then
    perform cron.unschedule('launch_social_refresh');
  end if;

  perform cron.schedule(
    'launch_social_refresh',
    '* * * * *',
    $job$select public.invoke_edge_job('launch-social-refresh');$job$
  );
end $$;
